# Train Test

In [1]:
import gymnasium as gym
from gymnasium.wrappers import RecordEpisodeStatistics, RecordVideo


env = gym.envs.make("Hockey-v0")


NameNotFound: Environment `Hockey` doesn't exist.

In [ ]:
import hockey.hockey_env as h_env

env = h_env.HockeyEnv_BasicOpponent(weak_opponent=False)

In [11]:
observation, info = env.reset()
while True:
    action = env.action_space.sample()
    observation, _, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        break

In [12]:
info

{'winner': 0,
 'reward_closeness_to_puck': -0.5198881360799305,
 'reward_touch_puck': 0.0,
 'reward_puck_direction': 0.0}

In [ ]:
ilist(range(0))

[]

In [4]:
from torchcodec.decoders import VideoDecoder


ModuleNotFoundError: No module named 'torchcodec'

In [1]:
from torchvision.io import read_video  # install av
clip = read_video("/Users/nargizi/Desktop/Uni/Masters/Reinforcement Learning/Project/RL-Hockey/src/crossq/vid/rl-video-episode-0.mp4")

/Users/nargizi/opt/anaconda3/envs/rl/lib/python3.12/site-packages/torchvision/io/_video_deprecation_warning.py:9: UserWarning: The video decoding and encoding capabilities of torchvision are deprecated from version 0.22 and will be removed in version 0.24. We recommend that you migrate to TorchCodec, where we'll consolidate the future decoding/encoding capabilities of PyTorch: https://github.com/pytorch/torchcodec
  warnings.warn(
/Users/nargizi/opt/anaconda3/envs/rl/lib/python3.12/site-packages/torchvision/io/video.py:199: UserWarning: The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.
  warnings.warn("The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.")


In [3]:
len(clip)

3

In [ ]:
import numpy as np

frames = np.array(list(clip.iter_frames()))


In [1]:
from sac import SACgent, SACConfig
agent = SACgent(SACConfig(device="mps"))
agent.train()

TypeError: QNetwork.__init__() missing 1 required positional argument: 'config'

In [1]:
from crossq import CrossQAgent, CrossQConfig
agent = CrossQAgent(CrossQConfig(device="mps", env_id="HalfCheetah-v5"))
agent.train()

tensor(-6., device='mps:0')


KeyboardInterrupt: 

In [3]:
import gymnasium as gym

In [7]:
env = gym.make("HalfCheetah-v5", render_mode="human")

# Reset the environment to generate the first observation
observation, info = env.reset(seed=42)
for _ in range(2000):
    # this is where you would insert your policy
    action = agent.act(observation=observation, deterministic=True)
    action = action.detach().cpu().numpy()

    # step (transition) through the environment with the action
    # receiving the next observation, reward and if the episode has terminated or truncated
    observation, reward, terminated, truncated, info = env.step(action)

    # If the episode has ended then we can reset to start a new episode
    if terminated or truncated:
        observation, info = env.reset()

env.close()

In [1]:
from crossq import QNetwork, GaussianPolicy, GaussianPolicyConfig, NNConfig, NormalizationConfig
import torch

In [2]:
import torch

models = torch.load("/Users/nargizi/Desktop/Uni/Masters/Reinforcement Learning/Project/RL-Hockey/models/crossq/100000/model.pkl", map_location=torch.device('cpu'))

In [116]:
score_pool = [1400, 1200, 1300, 900]


In [139]:
import gymnasium as gym
envs = gym.make_vec("HalfCheetah-v5", num_envs=10, vectorization_mode="sync")

In [148]:
a = np.array([True, False, True, False])
b = np.array([True, False, False, False])

In [154]:
a[np.newaxis, :].shape

(1, 4)

In [156]:
torch.from_numpy(a).unsqueeze(0).shape

torch.Size([1, 4])

In [145]:
a = np.array([envs.single_action_space.sample() for _ in range(envs.num_envs)])
b = np.array([envs.single_action_space.sample() for _ in range(envs.num_envs)]).shape

In [147]:
for ai, bi in zip(a[:], b[:]):
    print(ai.shape, bi.shape)

AttributeError: 'int' object has no attribute 'shape'

In [122]:
import numpy as np

scores = np.array(score_pool)
scores = scores / scores.sum()

In [125]:
scores

array([0.29166667, 0.25      , 0.27083333, 0.1875    ])

In [128]:
np.random.choice(range(len(score_pool)), p=(scores / scores.sum()))

np.int64(3)

In [2]:
q_funct = QNetwork(NNConfig(17 + 6, 512, 1, normalization_config=NormalizationConfig(type="BRN", warmup_steps=100_000)))

In [3]:
q_funct

QNetwork(
  (body): Sequential(
    (batchnorm0): BatchRenorm1d()
    (dense0): Linear(in_features=23, out_features=512, bias=True)
    (act0): ReLU()
    (batchnorm1): BatchRenorm1d()
    (dense1): Linear(in_features=512, out_features=512, bias=True)
    (act1): ReLU()
    (batchnorm2): BatchRenorm1d()
  )
  (output_layers): ModuleList(
    (0): Linear(in_features=512, out_features=1, bias=True)
  )
)

In [18]:
(512 * 2) ** 0.5

32.0

In [19]:
import itertools

In [ ]:
zipped = [(1, "a"), (2, "b"), (3, "c")]

In [28]:
a, b = itertools.tee(zip([1, 2], ["a", "b"]))
a, b = list(a), list(b)
a,b

([(1, 'a'), (2, 'b')], [(1, 'a'), (2, 'b')])

In [16]:
q_funct.body.dense1.weight.norm()

tensor(31.9599, grad_fn=<LinalgVectorNormBackward0>)

In [91]:
q_funct.body.dense1.weight.norm()

tensor(13.0632, grad_fn=<LinalgVectorNormBackward0>)

In [ ]:
weight = torch.rand((512, 512))
bias = torch.rand(512)

def forward(x, weight, bias):
    dense = weight @ x + bias
    relu = torch.nn.ReLU()(dense)
    return relu
    

In [73]:
import torch

torch.manual_seed(0)

D = 512
device = "cpu"
dtype = torch.float32

# Fixed layer params
weight = torch.rand((D, D), device=device, dtype=dtype) / D
bias = torch.rand((D,), device=device, dtype=dtype) 

relu = torch.nn.ReLU()

def forward(x, W, b):
    z = W @ x + b
    y = relu(z)
    return y, z

def dead_relu_percent_from_z(z: torch.Tensor) -> float:
    # dead = output == 0  <=>  z <= 0 for ReLU (ignoring exact zeros)
    return (z <= 0).float().mean().item() * 100.0

@torch.no_grad()
def estimate_dead_percent(W, b, n_samples=10_000, x_dist="normal"):
    dead = 0.0
    for _ in range(n_samples):
        if x_dist == "normal":
            x = torch.randn(D, device=device, dtype=dtype)
        elif x_dist == "uniform":
            x = torch.rand(D, device=device, dtype=dtype) * 2 - 1
        else:
            raise ValueError("x_dist must be 'normal' or 'uniform'")
        _, z = forward(x, W, b)
        dead += dead_relu_percent_from_z(z)
    return dead / n_samples

# ---------- Variants ----------
# 0) baseline
W0, b0 = weight.clone(), bias.clone()

# 1) "joint scaling": multiply both by same positive constant c
vec = torch.cat([W0.view(-1), b0.view(-1)])
c = 1 / vec.norm()
W_joint = c * W0
b_joint = c * b0

# 2) "joint norm normalization": scale both together to hit a target joint norm
target = 13
theta0 = torch.cat([W0.flatten(), b0.flatten()])
scale_joint = target / (theta0.norm() + 1e-12)
W_jointnorm = W0 * scale_joint
b_jointnorm = b0 * scale_joint

# 3) "weight-only normalization": scale W but keep b fixed  (THIS CAN CHANGE dead%)
scale_w_only = 0.1
W_wonly = W0 * scale_w_only
b_wonly = b0.clone()

# 4) "separate normalization": normalize W and b with different scalars (CAN CHANGE dead%)
target_w = 10.0
target_b = 10.0
scale_w = target_w / (W0.norm() + 1e-12)
scale_b = target_b / (b0.norm() + 1e-12)
W_sep = W0 * scale_w
b_sep = b0 * scale_b

# ---------- Run experiment ----------
n = 5000  # increase for tighter estimate

base = estimate_dead_percent(W0, b0, n_samples=n)
joint = estimate_dead_percent(W_joint, b_joint, n_samples=n)
jointnorm = estimate_dead_percent(W_jointnorm, b_jointnorm, n_samples=n)
wonly = estimate_dead_percent(W_wonly, b_wonly, n_samples=n)
sep = estimate_dead_percent(W_sep, b_sep, n_samples=n)

print(f"Dead ReLU % (baseline)            : {base:.4f}")
print(f"Dead ReLU % (joint scaling c={c}) : {joint:.4f}")
print(f"Dead ReLU % (joint norm target={target}) : {jointnorm:.4f}")
print(f"Dead ReLU % (weight-only scaling) : {wonly:.4f}")
print(f"Dead ReLU % (separate norming)    : {sep:.4f}")


Dead ReLU % (baseline)            : 1.2250
Dead ReLU % (joint scaling c=0.07682687789201736) : 1.2015
Dead ReLU % (joint norm target=13) : 1.2221
Dead ReLU % (weight-only scaling) : 0.0719
Dead ReLU % (separate norming)    : 22.9242


In [77]:
import torch
import torch.nn as nn

torch.manual_seed(0)

D = 512
B = 256
device = "cpu"
dtype = torch.float32

# Fixed params
W0 = torch.rand((D, D), device=device, dtype=dtype)
b0 = torch.rand((D,), device=device, dtype=dtype)

# Input batch (BN needs batch dimension)
X = torch.randn((B, D), device=device, dtype=dtype)

relu = nn.ReLU()

def dead_relu_percent_from_z(z: torch.Tensor) -> float:
    return (z <= 0).float().mean().item() * 100.0

def make_bn():
    # track_running_stats=False -> always uses batch stats; makes comparisons clean
    bn = nn.BatchNorm1d(D, affine=True, track_running_stats=False).to(device=device, dtype=dtype)
    bn.train()
    return bn

@torch.no_grad()
def forward_dense_relu_bn(X, W, b):
    bn = make_bn()  # fresh BN so baseline and variant use same init stats/params
    z = X @ W.T + b
    u = relu(z)
    y = bn(u)
    return y, z

@torch.no_grad()
def forward_dense_bn_relu(X, W, b):
    bn = make_bn()
    z = X @ W.T + b
    u = bn(z)
    y = relu(u)
    return y, z

# ----- Build variants -----
c = 0.1

variants = {}

# baseline
variants["baseline"] = (W0.clone(), b0.clone())

# joint scaling (cW, cb)
variants[f"joint scaling (c={c})"] = (c * W0, c * b0)

# joint norm target (scale both to hit target joint norm)
target_joint = 100.0
theta0 = torch.cat([W0.flatten(), b0.flatten()])
scale_joint = target_joint / (theta0.norm() + 1e-12)
variants[f"joint norm target={target_joint}"] = (W0 * scale_joint, b0 * scale_joint)

# weight-only scaling (cW, b)
variants[f"weight-only scaling (c={c})"] = (c * W0, b0.clone())

# separate norming (different scalars)
target_w = 10.0
target_b = 10.0
scale_w = target_w / (W0.norm() + 1e-12)
scale_b = target_b / (b0.norm() + 1e-12)
variants[f"separate norming (W->{target_w}, b->{target_b})"] = (W0 * scale_w, b0 * scale_b)

def compare_block(block_name, forward_fn):
    print(f"\n=== {block_name} ===")

    # baseline output
    y_base, z_base = forward_fn(X, *variants["baseline"])
    dead_base = dead_relu_percent_from_z(z_base)
    print(f"baseline dead% (pre-BN): {dead_base:.4f}")

    for name, (W, b) in variants.items():
        y, z = forward_fn(X, W, b)
        dead = dead_relu_percent_from_z(z)

        max_abs = (y - y_base).abs().max().item()
        mean_abs = (y - y_base).abs().mean().item()

        print(f"{name:35s}  max|Δ|={max_abs:.6e}  mean|Δ|={mean_abs:.6e}  dead% (pre-BN)={dead:.4f}")

compare_block("Dense → ReLU → BN", forward_dense_relu_bn)
compare_block("Dense → BN → ReLU", forward_dense_bn_relu)



=== Dense → ReLU → BN ===
baseline dead% (pre-BN): 51.2932
baseline                             max|Δ|=0.000000e+00  mean|Δ|=0.000000e+00  dead% (pre-BN)=51.2932
joint scaling (c=0.1)                max|Δ|=6.151199e-05  mean|Δ|=6.683530e-06  dead% (pre-BN)=51.2932
joint norm target=100.0              max|Δ|=1.096725e-05  mean|Δ|=6.576774e-07  dead% (pre-BN)=51.2939
weight-only scaling (c=0.1)          max|Δ|=1.125764e+00  mean|Δ|=1.538527e-01  dead% (pre-BN)=38.0608
separate norming (W->10.0, b->10.0)  max|Δ|=1.856599e+00  mean|Δ|=2.712933e-01  dead% (pre-BN)=23.9571

=== Dense → BN → ReLU ===
baseline dead% (pre-BN): 51.2932
baseline                             max|Δ|=0.000000e+00  mean|Δ|=0.000000e+00  dead% (pre-BN)=51.2932
joint scaling (c=0.1)                max|Δ|=1.454353e-05  mean|Δ|=1.189682e-06  dead% (pre-BN)=51.2932
joint norm target=100.0              max|Δ|=5.483627e-06  mean|Δ|=2.082108e-07  dead% (pre-BN)=51.2939
weight-only scaling (c=0.1)          max|Δ|=1.430511e-05

In [84]:
dict(q_funct.named_modules()).keys()

dict_keys(['', 'body', 'body.batchnorm0', 'body.dense0', 'body.act0', 'body.batchnorm1', 'body.dense1', 'body.act1', 'body.batchnorm2', 'output_layers', 'output_layers.0'])

In [86]:
[name for name, param in q_funct.named_parameters() if not "output_layers" in name ]

['body.batchnorm0.weight',
 'body.batchnorm0.bias',
 'body.dense0.weight',
 'body.dense0.bias',
 'body.batchnorm1.weight',
 'body.batchnorm1.bias',
 'body.dense1.weight',
 'body.dense1.bias',
 'body.batchnorm2.weight',
 'body.batchnorm2.bias']

In [87]:
[name for name, param in q_funct.output_layers.named_parameters()]

['0.weight', '0.bias']

In [81]:
for name, module in q_funct.named_modules():
    if "dense" in name:
        print(module)

Linear(in_features=23, out_features=512, bias=True)
Linear(in_features=512, out_features=512, bias=True)


In [58]:
vec = torch.cat([weight.view(-1), bias.view(-1)])
vec.norm()

tensor(296.1057)

In [50]:
torch.concat([q_funct.body.dense1.weight,
q_funct.body.dense1.bias.unsqueeze(-1)], dim=1).norm(p="fro")

tensor(13.0645, grad_fn=<LinalgVectorNormBackward0>)

In [5]:
q_funct.load_state_dict(models[1])

<All keys matched successfully>

In [22]:
q_funct.body.dense0.bias.norm()

tensor(5.1620, grad_fn=<LinalgVectorNormBackward0>)

In [21]:
(q_funct.body.dense0.bias > 0).norm()

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Bool

In [18]:
(q_funct.body.dense0.weight > 0).sum() / (512 * 23)

tensor(0.4950)

In [218]:
dict(q_funct.named_parameters()).keys()

dict_keys(['body.batchnorm0.weight', 'body.batchnorm0.bias', 'body.dense0.weight', 'body.dense0.bias', 'body.batchnorm1.weight', 'body.batchnorm1.bias', 'body.dense1.weight', 'body.dense1.bias', 'body.batchnorm2.weight', 'body.batchnorm2.bias', 'output_layers.0.weight', 'output_layers.0.bias'])

In [220]:
for name, parameter in q_funct.named_parameters():
            # only normalize non-finale dense layer's weights
            if "body" in name and "dense" in name and "weight" in name:
                    print(name)

body.dense0.weight
body.dense1.weight


In [215]:
[name for name, param in q_funct.output_layers.named_parameters() if "weight" in name]

['0.weight']

In [190]:
for mod_name, mod in q_funct.named_modules():
    # replicate your old filter but at module-level
    if ("body" in mod_name) and ("dense" in mod_name) and isinstance(mod, torch.nn.Linear):
        print(mod)
        # project_weight_to_norm_ball_(mod.weight, scale=scale)

Linear(in_features=23, out_features=2048, bias=True)
Linear(in_features=2048, out_features=2048, bias=True)


In [10]:
import torch

m = torch.rand((10, 10))
m.norm()

tensor(5.9129)

In [191]:
from torch.nn.utils import weight_norm
from torch.optim import SGD
from torch import nn

In [192]:
fc = nn.Linear(20, 1)
fc

Linear(in_features=20, out_features=1, bias=True)

In [193]:
wn_fc = weight_norm(fc,dim=None)

/Users/nargizi/opt/anaconda3/envs/rl/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [206]:
with torch.no_grad():
    wn_fc.weight_g.mul_( 1/ (wn_fc.weight_g.norm()))

In [209]:
wn_fc.weight.norm()

tensor(0.5947, grad_fn=<LinalgVectorNormBackward0>)

In [197]:
optimizer = SGD(wn_fc.parameters())

In [198]:
x = torch.rand(200, 20)
y = x.sum

In [199]:
x[-1]

tensor([0.0886, 0.2064, 0.8136, 0.7507, 0.9395, 0.6405, 0.5585, 0.1940, 0.7220,
        0.0332, 0.8530, 0.7946, 0.5565, 0.4441, 0.0891, 0.0659, 0.6469, 0.1750,
        0.6398, 0.8856])

In [200]:
y_pred = wn_fc(x)

In [204]:
wn_fc.weight.shape

torch.Size([1, 20])

In [164]:
loss = torch.nn.MSELoss()(y_pred, y)

In [165]:
loss

tensor(35106.6602, grad_fn=<MseLossBackward0>)

In [166]:
wn_fc.weight.norm()

tensor(1., grad_fn=<LinalgVectorNormBackward0>)

In [167]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [174]:
wn_fc.weight

tensor([[-0.2761, -0.1871, -0.2110, -0.2283, -0.2080, -0.1921, -0.2301, -0.2608,
         -0.1945, -0.1962, -0.2172, -0.1994, -0.2712, -0.2305, -0.2167, -0.2042,
         -0.2150, -0.2342, -0.1838, -0.2785]],
       grad_fn=<WeightNormInterfaceBackward0>)

In [169]:
with torch.no_grad():
    wn_fc.parametrizations.weight.original0.fill_(torch.sign(wn_fc.parametrizations.weight.original0).item())

In [187]:
with torch.no_grad():
    n = wn_fc.parametrizations.weight.original0.norm()
    wn_fc.parametrizations.weight.original0.mul_(1 / (n + 1e-12))

In [188]:
wn_fc.parametrizations.weight.original0

Parameter containing:
tensor(1., requires_grad=True)

In [181]:
wn_fc.parametrizations.weight.original1.shape

torch.Size([1, 20])

In [161]:
wn_fc.weight.norm()

tensor(1., grad_fn=<LinalgVectorNormBackward0>)

In [12]:
(m / m.norm()).norm()

tensor(1.)

In [ ]:
3e-4 / (400 ** 2)  
#  w_new / ||w_new|| = w / ||w|| - norm * ete_eff * grad
#  ||w_new - w || / ||w|| = ||w|| *eta_eff  ** ||grad||
#  ||w - w_new || / (||w||^2 * ||grad||) = eta_eff
#  w_new = w - eta * grad
# eta || grad || / 

1.875e-09

In [7]:
[layer_name for layer_name in dict(q_funct.named_parameters()).keys() if ("dense" in layer_name or "output_layers" in layer_name) and "weight" in layer_name]

['body.dense0.weight', 'body.dense1.weight', 'output_layers.0.weight']

In [6]:
dict(q_funct.named_modules()).keys()

dict_keys(['', 'body', 'body.batchnorm0', 'body.dense0', 'body.act0', 'body.batchnorm1', 'body.dense1', 'body.act1', 'body.batchnorm2', 'output_layers', 'output_layers.0'])

In [15]:
dict(q_funct.named_parameters()).keys()

dict_keys(['body.batchnorm0.weight', 'body.batchnorm0.bias', 'body.dense0.weight', 'body.dense0.bias', 'body.batchnorm1.weight', 'body.batchnorm1.bias', 'body.dense1.weight', 'body.dense1.bias', 'body.batchnorm2.weight', 'body.batchnorm2.bias', 'output_layers.0.weight', 'output_layers.0.bias'])

In [22]:
policy = GaussianPolicy(torch.tensor([0, 0, 0, 0, 0, 0]), torch.tensor([1, 1, 1, 1, 1, 1]), GaussianPolicyConfig(17, 256, action_dim=6))

In [23]:
policy.load_state_dict(models[0])

<All keys matched successfully>

In [30]:
policy.body[0].__dict__

{'training': True,
 '_parameters': {'weight': Parameter containing:
  tensor([0.9385, 1.7857, 0.8400, 0.4868, 0.3540, 0.8495, 0.6044, 0.3469, 0.9546,
          0.6458, 0.9515, 0.9454, 0.5609, 0.2762, 0.7820, 0.5235, 0.2850],
         requires_grad=True),
  'bias': Parameter containing:
  tensor([ 0.1370,  0.1721,  0.0551, -0.1129,  0.1324, -0.2459, -0.1588,  0.0132,
           1.2855,  0.0092,  0.0883, -0.0728,  0.0528, -0.1133, -0.0657, -0.0842,
          -0.1793], requires_grad=True)},
 '_buffers': {'running_mean': tensor([-0.0319,  0.1900,  0.0881, -0.2974, -0.1506, -0.1657, -0.0491,  0.0125,
           7.8394, -0.0376, -0.0471,  0.0799, -0.0180,  0.0290,  0.0527, -0.0090,
           0.0357]),
  'running_var': tensor([7.5692e-03, 9.6954e-01, 2.4591e-01, 8.9798e-02, 7.7591e-02, 2.1541e-01,
          1.5975e-01, 1.0016e-01, 1.3004e+01, 4.6535e-01, 3.7729e+00, 8.8515e+01,
          4.9334e+01, 3.8337e+01, 8.0428e+01, 7.2349e+01, 4.0705e+01]),
  'num_batches_tracked': tensor(66667)},
 '

In [204]:
import gymnasium as gym

from memory import Memory

memory = Memory()

# Initialise the environment
env = gym.make("Pendulum-v1")

In [205]:
torch.device("mps")

device(type='mps')

In [206]:
import numpy as np
import torch
obs_dim = np.prod(env.observation_space.shape)
action_dim = np.prod(env.action_space.shape)
q_functions = [ QNetwork(observation_dim=obs_dim, action_dim=action_dim,hidden_dim=2048, 
                         normalization=torch.nn.BatchNorm1d(num_features=2048, momentum=.99)
                         ) for _ in range(2)]
policy = GaussianPolicy(min_action=torch.from_numpy(env.action_space.low), max_action=torch.from_numpy((env.action_space.high)), 
                                     observation_dim=obs_dim, action_dim=action_dim, hidden_dim=256)

In [207]:
device = "mps"

In [208]:
policy.to(device)
q_functions[0].to(device)
q_functions[1].to(device)

QNetwork(
  (model): Sequential(
    (0): Linear(in_features=4, out_features=2048, bias=True)
    (1): ReLU()
    (2): BatchNorm1d(2048, eps=1e-05, momentum=0.99, affine=True, track_running_stats=True)
    (3): Linear(in_features=2048, out_features=2048, bias=True)
    (4): ReLU()
    (5): BatchNorm1d(2048, eps=1e-05, momentum=0.99, affine=True, track_running_stats=True)
    (6): Linear(in_features=2048, out_features=1, bias=True)
  )
)

In [209]:
import time
def compute_critic_loss(q_functions: list[QNetwork], policy: GaussianPolicy, alpha, gamma,
                        observations, 
                        actions, 
                        rewards, next_observations, finished):
    

    # return ((q_functions[0].q_value(observations, actions) - rewards) ** 2).mean()
    
    start_time = time.time()
    next_actions, log_prob = policy.get_action(next_observations)
    # print(f"BATCH POLICY {time.time() - start_time}")


    start_time = time.time()
    qs = torch.stack([q_func.q_value(torch.concat([observations, next_observations]), torch.concat([actions, next_actions])) for q_func in q_functions]).squeeze(-1)
    # print(f"BATCH Q {time.time() - start_time}")

    # print(len(torch.split(qs, 32, dim=1)))
    q, next_q = torch.split(qs, qs.shape[1] // 2, dim=1)

    next_q = torch.min(next_q, dim=0).values

    with torch.no_grad():
        next_q = next_q - alpha * log_prob.squeeze(-1)

    return ((q - (rewards + gamma * next_q * (1 - finished))) ** 2).mean()


def compute_actor_loss(q_functions: list[QNetwork], policy: GaussianPolicy, alpha,
                        observations, 
                        actions, 
                       ):
    _, log_prob = policy.get_action(observations)

    qs = torch.stack([q_func.q_value(observations, actions) for q_func in q_functions])

    q_value = torch.min(qs, dim=0).values

    return -(q_value - alpha * log_prob).mean()

In [210]:
from torch import  optim
q_optimizer = optim.Adam(list(q_functions[0].parameters()) + list(q_functions[1].parameters()), lr=1e-3)
actor_optimizer = optim.Adam(list(policy.parameters()), lr=1e-3)

In [211]:
memory = Memory()


In [212]:
# observation, reward, terminated, action, next_observation = memory.sample(256).T
# actions = torch.from_numpy(np.stack(action)).to(device)
# next_observations = torch.from_numpy(np.stack(next_observation)).to(device)
# observations = torch.from_numpy(np.stack(observation)).to(device)
# terminateds = torch.from_numpy(np.stack(terminated)).to(torch.float32).to(device)
# rewards = torch.from_numpy(np.stack(reward)).to(torch.float32).to(device)

# q_functions[0].q_value(observations, actions)

In [213]:

# rewards

In [214]:
# Reset the environment to generate the first observation

import time

def fit(step: int, delay: int = 3):
    observation, reward, terminated, action, next_observation = memory.sample(256).T


    action = torch.from_numpy(np.stack(action)).to(device)
    next_observation = torch.from_numpy(np.stack(next_observation)).to(device)
    observation = torch.from_numpy(np.stack(observation)).to(device)
    terminated = torch.from_numpy(np.stack(terminated)).to(torch.float32).to(device)
    reward = torch.from_numpy(np.stack(reward)).to(torch.float32).to(device)

    critic_loss = compute_critic_loss(q_functions, policy, .2, .99, observation, action, reward, next_observation, terminated)

    q_optimizer.zero_grad()
    critic_loss.backward()
    q_optimizer.step()

    if step % 50 == 0:
        print(f"CRITIC LOSS At {step} :", critic_loss.item())

    if step % delay == 0:
        for _ in range(delay):

            actor_loss = compute_actor_loss(q_functions, policy, .2, observation, action)

            actor_optimizer.zero_grad()
            actor_loss.backward()
            actor_optimizer.step()
            # print(actor_loss.item())
            ...
    




observation, info = env.reset(seed=42)
step = 0
for epoch in range(5):
    rewards = []
    for _ in range(1_000):
        step += 1
        # this is where you would insert your policy
        # start_time = time.time()
        action, _ = policy.get_action(observations=torch.from_numpy(observation).to(device))
        action = action.detach().cpu().numpy()
        
        # step (transition) through the environment with the action
        # receiving the next observation, reward and if the episode has terminated or truncated
        next_observation, reward, terminated, truncated, info = env.step(action)
        rewards.append(reward)

        observation = next_observation

        if terminated:
            observation = env.reset()

        memory.add_transition([observation, reward, terminated, action, next_observation])

        # train part
        fit(step)

    print(np.stack(rewards).mean().item())
 
# env.close()

CRITIC LOSS: 8.505910873413086
CRITIC LOSS: 902.74462890625
CRITIC LOSS: 202.15206909179688
CRITIC LOSS: 73.65800476074219
CRITIC LOSS: 27.107715606689453
CRITIC LOSS: 18.44860076904297
CRITIC LOSS: 30.350191116333008
CRITIC LOSS: 42.38352584838867
CRITIC LOSS: 74.83926391601562
CRITIC LOSS: 43.504878997802734
CRITIC LOSS: 71.53836822509766
CRITIC LOSS: 47.712860107421875
CRITIC LOSS: 48.17757034301758
CRITIC LOSS: 48.51508712768555
CRITIC LOSS: 48.545021057128906
CRITIC LOSS: 34.487884521484375
CRITIC LOSS: 29.749479293823242
CRITIC LOSS: 30.60016632080078
CRITIC LOSS: 24.960281372070312
CRITIC LOSS: 25.058393478393555
CRITIC LOSS: 21.530534744262695
CRITIC LOSS: 19.566797256469727
CRITIC LOSS: 17.91006851196289
CRITIC LOSS: 17.08014678955078
CRITIC LOSS: 15.794222831726074
CRITIC LOSS: 15.91260051727295
CRITIC LOSS: 16.36075782775879
CRITIC LOSS: 20.131052017211914
CRITIC LOSS: 23.71172523498535
CRITIC LOSS: 23.54078483581543
CRITIC LOSS: 19.01782989501953
CRITIC LOSS: 17.23443603515

KeyboardInterrupt: 

In [216]:
env = gym.make("Pendulum-v1", render_mode="human")

# Reset the environment to generate the first observation
observation, info = env.reset(seed=42)
for _ in range(1000):
    # this is where you would insert your policy
    action, _ = policy.get_action(observations=torch.from_numpy(observation).to(device))
    action = action.detach().cpu().numpy()

    # step (transition) through the environment with the action
    # receiving the next observation, reward and if the episode has terminated or truncated
    observation, reward, terminated, truncated, info = env.step(action)

    # If the episode has ended then we can reset to start a new episode
    if terminated or truncated:
        observation, info = env.reset()

env.close()

In [ ]:
q_functions[0]

QNetwork(
  (model): Sequential(
    (0): Linear(in_features=4, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): ReLU()
    (4): Linear(in_features=256, out_features=1, bias=True)
  )
)

In [ ]:
policy

GaussianPolicy(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): ReLU()
    (4): Linear(in_features=256, out_features=256, bias=True)
    (5): ReLU()
  )
  (fc_mean): Linear(in_features=256, out_features=1, bias=True)
  (fc_std): Linear(in_features=256, out_features=1, bias=True)
)

In [ ]:
actor

Actor(
  (fc1): Linear(in_features=3, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=256, bias=True)
  (fc_mean): Linear(in_features=256, out_features=1, bias=True)
  (fc_logstd): Linear(in_features=256, out_features=1, bias=True)
)

In [ ]:
actor.get_action()

In [25]:
next_action, log_prob = policy.get_action(next_observation)

In [28]:
torch.concat([action, next_action])

tensor([[0.5134],
        [1.1025],
        [0.4588],
        [0.1934]], grad_fn=<CatBackward0>)

In [37]:
qs = torch.stack([q_func.q_value(torch.concat([observation, next_observation]), torch.concat([action, next_action])) for q_func in q_functions])
qs

tensor([[[ 0.0371],
         [ 0.0396],
         [ 0.2534],
         [ 0.0683]],

        [[-0.0111],
         [ 0.0231],
         [-0.1929],
         [-0.0512]]], grad_fn=<StackBackward0>)

In [50]:
q, next_q = torch.split(qs, 2, dim=1)

In [54]:
next_q = torch.min(next_q, dim=0).values
next_q

tensor([[-0.1929],
        [-0.0512]], grad_fn=<MinBackward0>)

In [56]:
alpha = 0.5

In [57]:
with torch.no_grad():
    next_q = next_q - alpha * log_prob

next_q

tensor([[0.7734],
        [0.5635]])

In [61]:
(q - (reward + 0.99 * next_q) ** 2).mean()

tensor(-90.1007, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [43]:
q

tensor([[[ 0.0371],
         [ 0.0396]],

        [[-0.0111],
         [ 0.0231]]], grad_fn=<SplitBackward0>)

In [7]:
q_functions[0]

QNetwork(
  (model): Sequential(
    (0): Linear(in_features=4, out_features=2048, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2048, out_features=2048, bias=True)
    (3): ReLU()
    (4): Linear(in_features=2048, out_features=1, bias=True)
  )
)

graph(%self.1 : __torch__.___torch_mangle_14.DummyModel,
      %x : Float(2, 10, strides=[10, 1], requires_grad=0, device=cpu)):
  %fc2 : __torch__.torch.nn.modules.linear.___torch_mangle_12.Linear = prim::GetAttr[name="fc2"](%self.1)
  %act_func : __torch__.torch.nn.modules.activation.___torch_mangle_13.ReLU = prim::GetAttr[name="act_func"](%self.1)
  %fc1 : __torch__.torch.nn.modules.linear.___torch_mangle_11.Linear = prim::GetAttr[name="fc1"](%self.1)
  %bias.1 : Tensor = prim::GetAttr[name="bias"](%fc1)
  %weight.1 : Tensor = prim::GetAttr[name="weight"](%fc1)
  %input.1 : Float(2, 50, strides=[50, 1], requires_grad=1, device=cpu) = aten::linear(%x, %weight.1, %bias.1), scope: __module.fc1 # /Users/nargizi/opt/anaconda3/envs/rl/lib/python3.12/site-packages/torch/nn/modules/linear.py:134:0
  %input : Float(2, 50, strides=[50, 1], requires_grad=1, device=cpu) = aten::relu(%input.1), scope: __module.act_func # /Users/nargizi/opt/anaconda3/envs/rl/lib/python3.12/site-packages/torch/nn/